/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BehandlungenRouteImport } from './routes/behandlungen'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BehandlungenRoute = BehandlungenRouteImport.update({
  id: '/behandlungen',
  path: '/behandlungen',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/behandlungen': typeof BehandlungenRoute
  '/ueber-uns': typeof UeberUnsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/behandlungen': typeof BehandlungenRoute
  '/ueber-uns': typeof UeberUnsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/behandlungen': typeof BehandlungenRoute
  '/ueber-uns': typeof UeberUnsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/behandlungen' | '/ueber-uns'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/behandlungen' | '/ueber-uns'
  id: '__root__' | '/' | '/behandlungen' | '/ueber-uns'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BehandlungenRoute: typeof BehandlungenRoute
  UeberUnsRoute: typeof UeberUnsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/behandlungen': {
      id: '/behandlungen'
      path: '/behandlungen'
      fullPath: '/behandlungen'
      preLoaderRoute: typeof BehandlungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BehandlungenRoute: BehandlungenRoute,
  UeberUnsRoute: UeberUnsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
